# -*- mode: ruby -*-
# vi: set ft=ruby :
# About: Vagrant file for the development environment

###############
#  Variables  #
###############

CPUS = 4
RAM = 8096

# Bento: Packer templates for building minimal Vagrant baseboxes
# The bento/ubuntu-XX.XX is a small image of about 500 MB, fast to download
BOX = "bento/ubuntu-22.04"
VM_NAME = "ubuntu-22.04-satcon"

######################
#  Provision Script  #
######################

# Common bootstrap
$bootstrap= <<-SCRIPT
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

APT_PKGS=(
  ansible
  bash-completion
  dfc
  gdb
  git
  htop
  iperf
  iperf3
  make
  pkg-config
  python3
  python3-dev
  python3-pip
  sudo
  tmux
)
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${APT_PKGS[@]}"
SCRIPT

$setup_x11_server= <<-SCRIPT
APT_PKGS=(
  openbox
  xauth
  xorg
  xterm
)
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y "${APT_PKGS[@]}"
SCRIPT


$setup_satcon= <<-SCRIPT
cd /home/vagrant/satellite_constellation || exit
bash ./install.sh -a

SCRIPT


$post_installation= <<-SCRIPT
# Allow the vagrant user to use Docker without sudo.
usermod -aG docker vagrant
if [ -d /home/vagrant/.docker ]; then
  chown -R vagrant:vagrant /home/vagrant/.docker
fi
DEBIAN_FRONTEND=noninteractive apt-get autoclean -y
DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
SCRIPT

####################
#  Vagrant Config  #
####################

Vagrant.configure("2") do |config|

  config.vm.define "satcon" do |satcon|
    satcon.vm.box = BOX
    # Sync ./ to home directory of vagrant to simplify the install script
    satcon.vm.synced_folder ".", "/vagrant", disabled: true
    satcon.vm.synced_folder ".", "/home/vagrant/satellite_constellation"

    # For Virtualbox provider
    satcon.vm.provider "virtualbox" do |vb|
      vb.name = VM_NAME
      vb.cpus = CPUS
      vb.memory = RAM
      # MARK: The vCPUs should have SSE4 to compile DPDK applications.
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
    end

    satcon.vm.hostname = "satcon"
    satcon.vm.box_check_update = true
    satcon.vm.post_up_message = '
The VM is up! Run "$ vagrant ssh satcon" to ssh into the running VM.

IMPORTANT! For all ComNetsEmu users and developers:

Have Fun :)
    '

    satcon.vm.provision :shell, inline: $bootstrap, privileged: true
    satcon.vm.provision :shell, inline: $setup_x11_server, privileged: true
    satcon.vm.provision :shell, inline: $setup_satcon, privileged: false
    satcon.vm.provision :shell, inline: $post_installation, privileged: true

    # VM networking
    satcon.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1"
    satcon.vm.network "forwarded_port", guest: 8082, host: 8082
    satcon.vm.network "forwarded_port", guest: 8083, host: 8083
    satcon.vm.network "forwarded_port", guest: 8084, host: 8084

    # - Uncomment the underlying line to add a private network to the VM.
    #   If VirtualBox is used as the hypervisor, this means adding or using (if already created) a host-only interface to the VM.
    # satcon.vm.network "private_network", ip: "192.168.0.2"

    # Enable X11 forwarding
    satcon.ssh.forward_agent = true
    satcon.ssh.forward_x11 = true
  end
end
